name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build image
        run: |
          python build.py
          docker image ls quay.io/ansible/ansible-runner-test-container
          docker history quay.io/ansible/ansible-runner-test-container
